---
title: "TREAT Accrual Report"
output:
  word_document: null
  html_document: default
date: "October 28, 2016"
---

1.	TREAT-001 -- Observational 
2.	TREAT-002 -- IU Obeticholic Acid 
3.	TREAT-003 -- VCU Immuron 
4.	TREAT-008 -- Cohort Dose Escalation Study  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pander)
```

```{r, echo=FALSE}
accrualGraph = function(ondate, startdate, enddate=Sys.Date(), expmnth=0) {
  #install pacakges (if not installed) and load
  packages <- c("ggplot2", "scales")
  if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
    install.packages(setdiff(packages, rownames(installed.packages())))  
  }  
  library(ggplot2)
  library(scales)
  
  #Build monthly buckets of actual accrual
  mnths = seq(startdate, enddate, by="month")
  
  # create variables of the week and month of each observation:
  enroll <- data.frame(ondate)
  enroll$Month <- as.Date(cut(as.Date(enroll$ondate,format="%m/%d/%Y"),breaks = "month"))
  enroll$Count = 1
  
  #possible that a month would not have any enrollment, need to add months with no enrollment
  dmnth = as.Date(unique(enroll$Month))
  addmnth = mnths[!mnths %in% dmnth]
  enroll2 = enroll
  enroll2[(nrow(enroll)+1):(nrow(enroll)+length(addmnth)),"Month"] = addmnth
  enroll2[(nrow(enroll)+1):(nrow(enroll)+length(addmnth)),"Count"] = 0
  
  # sum by month and assign total for each month into Accrual vector, since month buckets
  # are summed into beginning of first month, need to move sums one month over for end-of-month
  msum = c(0,cumsum(as.vector(unlist(tapply(enroll2$Count,enroll2$Month,sum)))))
  
  mnths = append(mnths, enddate)
  acc = data.frame(mnths,msum)
  acc$accgrp="Actual"
  
  #append expected month sequence into graph data if it was passed to function
  if(!expmnth==0){
    expdf = data.frame(mnths,msum=seq(from=0,to=(expmnth*(nrow(acc)-1)),by=expmnth),accgrp="Expected")
    acc = rbind(acc, expdf)
  }
  
  # graph by month:
  ggplot(data = acc, aes(mnths, msum,group=accgrp,colour=accgrp)) +
    geom_line(aes(linetype=accgrp)) +
    geom_point()  +
    xlab("Accrual Date") + ylab("Number of Patient Accrued") +
    scale_colour_discrete(name="") +    
    scale_linetype_discrete(name="")    
}
```

## TREAT 001

```{r, echo=FALSE}

#read xls or xlsx
library("readxl")

demog <- read_excel("I:/Projects/TREAT/Data Management/Reports/Enrollment Reports/data/Demographics_001.xlsx")
# demog <- read.delim("I:/Projects/TREAT/Data Management/Reports/Enrollment Reports/data/Demographics_001.txt")
demog2 = demog[which(demog$ARMS == "CASES"),]

ondate = as.Date(na.omit(demog2$ON_STUDY_DATE), origin="1899-12-30")
#ondate = as.Date(demog$ON_STUDY_DATE, format="%m/%d/%Y")

#Code as function with arguments (on study dates, start date, end date, 
#  optional expected n per month )
accrualGraph(ondate,startdate=as.Date("2013-06-01"),expmnth=7)

```


```{r, echo=FALSE}
Site=c("IU","Mayo","VCU", "Total")
IU = c("Fairbanks Drug and Alcohol Rehabilitation Hospital", "Indiana University Hospital / IU Simon Cancer Center", "Eskenazi Hospital")
Mayo = "Mayo Clinic"
VCU = "Virginia Commonwealth University (VCU)"
# enrollment numbers by site and total for CASES
Cases=c(length(which(demog2$STUDY_SITE %in% IU)),length(which(demog2$STUDY_SITE %in% Mayo)), length(which(demog2$STUDY_SITE %in% VCU)),
          length(which(demog$ARMS == "CASES")))
pander(data.frame(Site,Cases))

```

## TREAT 002

```{r, echo=FALSE}

demog <- read_excel("I:/Projects/TREAT/Data Management/Reports/Enrollment Reports/data/Demographics_002.xlsx")
# demog <- read.delim("I:/Projects/TREAT/Data Management/Reports/Enrollment Reports/data/Demographics_001.txt")
# Code as function with arguments (on study dates, start date, end date, 
#  optional expected n per month )
ondate = as.Date(na.omit(demog$ON_STUDY_DATE), origin="1899-12-30")
#ondate = as.Date(demog$ON_STUDY_DATE, format="%m/%d/%Y")
accrualGraph(ondate,startdate=as.Date("2013-06-01"),expmnth=4.5)

```
